Updated README.md
EasyEngine/shell-command pull request #8
Opened 2018-09-13 08:00 UTC by sagarnasit

2018-09-14 15:31 UTC, mbtamuli requested changes
Need to add examples.

2018-09-17 06:30 UTC, sagarnasit commented
Done.

2018-09-17 06:30 UTC, sagarnasit commented
Done.

2018-09-17 12:49 UTC, mbtamuli approved these changes

2018-09-17 12:50 UTC, merged